# Site settings
title: "Ahmed Mostafa Portfolio" # Your site's title
email: "newahmed1672022@gmail.com" # Replace with your email address
description: > # This means to ignore newlines until "baseurl:"
  Welcome to my portfolio! Showcasing my expertise in NLP, machine learning, and deep learning projects.
baseurl: "" # Leave empty for root deployment
url: "https://AhmedMostafa167.github.io" # Replace <your-username> with your GitHub username

github_username: "AhmedMostafa167" # Replace with your GitHub username

# Build settings
markdown: kramdown
